// <auto-generated />
namespace legion_service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_sensor_Data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_sensor_Data));
        
        string IMigrationMetadata.Id
        {
            get { return "201507310000465_new_sensor_Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
