// <auto-generated />
namespace legion_service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alt_enum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alt_enum));
        
        string IMigrationMetadata.Id
        {
            get { return "201507302344270_alt_enum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
